version: 2
jobs:
  build:
    working_directory: ~/schema_conformist
    docker:
      - image: circleci/ruby:2.4.2
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: schema_conformist-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: schema_conformist-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: (cd test/dummy && bin/rake db:create db:migrate)
      - run: bin/test
      - store_test_results:
          path: test_results
